# Generated by Django 4.2 on 2024-08-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
