# Generated by Django 4.1.7 on 2023-02-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Game', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='life',
            field=models.CharField(blank=True, default='1 Days', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='200.00', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='200.00', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='X vs Y', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='permier league', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='chat_resp_time',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='days_return',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_on_time',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='Kebebew', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
