# Generated by Django 4.2 on 2024-08-12 15:28

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coupon_cartorder_address_cartorder_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='coupons',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tracking_website_address',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='email',
            field=models.EmailField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='paid_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', blank=True, length=5, max_length=20, null=True, prefix='SKU'),
        ),
    ]
