# Generated by Django 4.2 on 2024-08-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cartorder_address_cartorder_city_cartorder_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Not Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Not Paid', max_length=30),
        ),
    ]
