# file created: 2022-07-17 21:12:55.135568

# this files has been generated by XXXXXXXX.XXX  Please do not change manually
# author: Next Level Sense

# Available functions:
#    render - replacement for django render function
#    path - replacement for django path function. please use with * when replacing in urls.py
#    supported_languages - list that contains all available languages for this site
# Functions to be used in django templates:
#    languageReferences - create 'alternate' language references for SEO.
#        put it inside of the <head> section of the page in format {{languageReferences|safe}}
#    lang - current language. Used mostly in <html lang="{{lang}}">
#    languageMenu - adding language selection for your page. Format: {{languageMenu|safe}}
#    <<link variables>> - create linking to correct language link. 
#    usage:
#    for translated pages change {% url "my_page" %}
#    to name without quotes:     {% url my_page %}


supported_languages = ['en', 'de', 'es']

def translation_dictionary(lang):
    if lang == 'en': return {
        




              'all_main':'''ተገገገረሀረሀተ''',
        'all_home':'''ብይት''',
       
         'all_pages':'''ገጥ''',
         'all_aboutus':'''ስለኛ''',
         'all_aboutus1':'''እንኳን ወደ አፍሮ ሶከር ኢትዮጵያ በሰላም መጣቹ''',

         'all_aboutus2':'''አፍሮ ሶከር ኢትዮጵያ በኢትዮጵያ እግር ኳስ ላይ ትኩረቱን አድርጎ የሚሰራ የኦንላይን ሚድያ ነው።sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate id est laborum.''',

         'all_aboutus3':'''Ius ferri velit sanctus cu, sed at soleat accusata. Dictas prompta et Ut placerat legendos interpre.Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante Etiam sit amet orci eget. Quis commodo odio aenean sed adipiscing. Turpis massa tincidunt dui ut ornare lectus. Auctor elit sed vulputate mi sit amet. Commodo consequat. Duis aute irure dolor in reprehenderit in voluptate id est laborum.''',

        'all_aboutus4':'''What We Provide? አቅርቦታችን''',
       'all_aboutus5':'''ምርጥ እቅርቦት''',
        'all_aboutus6':'''ብዚሀ ግጥ  እናንትነ የሚየስተምሩ but the majority have suffered alteration in some form''',
             'all_aboutus7':'''የብልጠ እንብብ''',
              'all_aboutus8':'''ተልቅ ሰጦታ''',
               'all_aboutus9':'''here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form''',
               
                 'all_aboutus11':'''ስለ ሽቀረቦታችን


                  ''',

                   'base':'''አፍሮ ሶከር ኢትዮጵያ''',
 'all_base1':'''Sale Off''',
 'all_base2':'''Add to cart''',
 'all_base3':'''Vendor''',
 'all_base4':'''FOOTBALL''',
 'all_base5':'''>MFG:''',
 'all_base6':''' Jun 4.2022''',

 'all_base7':''' የህገር ዉስጥ ተጫዋቾችን ''',
 'all_base8':''' ስለእኛ''',
 'all_base9':'''wu''',

 'all_base10':'''አግኙን
 ''',
 'all_base11':'''አፍር ሶከር ኢትዮጵያ የናንተ ምርጫ''',

 'all_base12':'''የህገር ዉስጥ ተጫዋቾችን ለአለም እናስተዋውቃለን''',
 'all_base13':'''ምርጫቹ ስላደረርጋቹን እናመሰግናለለን''',
 'all_base14':''' የክብር ስፖንሰር-፟ቡና ኢንተርናሽናል ባንከ''',
 'all_base15':'''እገዛ ከፈለጉ?የደዉሉልን::''',
 'all_base16':'''ሁሉምክፍል
 ''',
 'all_base17':'''Football''',
 'all_ baseacc':'''እካዉነትይ
 ''',











 'all_baseh':'''የእኢትየኦጵየ ተጫዋቾች''',
 'all_baser':'''የ 2015 የኢትዮጽያ ፕርሚየርሊግ ውጤት
  ''',
 'all_basen':'''ስፖርት ዘና''',
'all_basen1':'''ወቅታዊ የስፖርት ዜና''',
'all_basen1':'''ወቅታዊ የስፖርት ዜና''',
   'all_basen2':'''ወቅታዊ የዝውውር ዜና''',
 'all_basen4':'''የሳምንቱ ምርጥ ተጫዋች''',

                
'all_baset':'''የዝውውር ዝና''',
 'all_basep':''' የኢትየጵየ ተጫዋቾች''',
'all_basecl':''' የኢትየጵየ ክልቦች''',
  'all_basec':'''EPL አሰልጣኞች''',
  'all_basez':'''የእግር ኩዋስ ሽልማት''',
  'l_base':'''ሪቪው''',

 






   



 'all_basep0':'''እአቡበከር ኡመር''',
    'all_basep2':'''ምኞት ደበበ''',
 'all_basep3':'''ገታነህ ከበደ''',
  'all_basep4': '''ኡመድ ኡክሪ''',
   'all_basep5':'''ሱለይማን ሃሚድ''',
   'all_basep6':'''አስቻለዉ ታመነ''',
   'all_basep7': '''ሽመልስ በቀለ''',
  'all_basep8': '''ምኞት ደበበ''',
   'all_basep9':'''ዳዊት እስጢፋኖስ''',
   'all_basep10':'''ረመዳን ዩሱፍ''',
    'all_basep11':'''ቢኒያም ከበደ''',
 'all_basep12':'''   ሳላዲን በርጋቾ''',
  'all_basep13':'''አማኑእል ግ/ሚካእል''',
    'all_basep14':'''ፍጡም አልሙ''',
  'all_basep15': '''ሙጂብ ቃሲም''',
   'all_basep16':  '''ስቻለዉ ታመነ''',
   'all_basep7': '''ሽመልስ በቀለ''',
  'all_basep17': '''መሱድ ሙሃመድ''',
   'all_basep18':'''በዛብህ መለዮ''',
   'all_basep19': '''በረከት እማረ''',

     'all_basep20': '''አበበ ለማ''',







'all_basec0':'''ኢትዮጵያ ቡና''',
    'all_basec2':'''ወላይታ ዲቻ''',
 'all_basec3':'''ወላይታ ዲቻ''',
  'all_basec4': '''ሃዋሳ ከነማ''',
   'all_basec5':'''ሃዲያ ሆሳና''',
   'all_basec6':'''መከላከያ''',
   'all_basec7': '''ወላይታ ዲቻ''',
  'all_basec8': '''ፋሲል ከነማ''',
   'all_basec9':'''ሲዳማ ቡና''',
   'all_basec10':'''ቅ/ጊ''',
    'all_basec11':'''ፋሲል ከነማ''',
 'all_basec12':'''  አዳማ ከነማ''',
  'all_basec13':'''ባህርዳር ከነማ''',
    'all_basec14':'''>ወላይታ ዲቻ''',
  'all_basec15': '''ቅ/ጊ''',
   'all_basec16':  '''ሲዳማ ቡና''',
   'all_basec7': '''አዳማ ከነማ''',
  'all_basec17': '''አርባምንጭ ቢራ''',
   'all_basec18':'''ዳሸን ቢራ''',
   'all_basec19': '''ደቡብ ፖሊስ''',

     'all_basec20': '''ድረደዋ''',





'all_basecl0':'''ዉበቱ አባተ''',
    'all_basecl2':'''አብርሃም መብራቱ''',
 'all_basecl3':'''ዮህንስ ሳህለ''',
  'all_basecl4': '''ይድነቃቸው ተሰማ''',
   'all_basecl5':'''ገብረመድህን ሃይለ''',
   'all_basecl6':'''መንግስቱ ወርቁ''',
   'all_basecl7': '''አሸናፊ በቀለ''',
  'all_basecl8': '''ዮህንስ ሳህለ''',
   'all_basecl9':'''ገብረመድህን ሃይለ''',
   'all_basecl10':'''አብርሃም መብራቱ''',
    'all_basecl11':'''ዉበቱ አባተ''',
 'all_basecl12':'''  አሸናፊ በቀለ''',
  'all_basecl13':'''ገብረመድህን ሃይለ''',
    'all_basecl14':'''ዮህንስ ሳህለ''',
  'all_basecl15': '''ገብረመድህን ሃይለ''',
   'all_basecl16':  '''አብርሃም መብራቱ''',
   'all_basecll7': '''ዉበቱ አባተ''',
  'all_basec17': '''አሸናፊ በቀለ''',
   'all_basecl18':'''ገብረመድህን ሃይለ''',
   'all_basecl19': '''ዮህንስ ሳህለ''',

     'all_basecl20': '''ዮህንስ ሳህለ''',
     'all_basesup': '''የእገዛ ማእከል''',




'SUMMERY':'''ማጠቃለያ''',
'RESULTS':'''ውጤት''',

'FIXTURES':'''መግጠሚያ''',

'STANDING':'''አቋቋም''',

'ACHIVE':'''ማሳካት''',
 'all_basekk': '''አፍሮ ሶከር  የኢትዮጽያ ''',



        'all_implementation':'''Implementierung''',
        'all_contact':'''Kontakt''',
        'home_title':'''Übersetzungsrahmen für Django''',
        'home_description':'''Dies ist nur ein Beispiel für eine mehrsprachige Website''',
        'home_subject':'''Süßigkeiten übersetzen''',
        'home_info':'''Einfache und schnelle Möglichkeit, der Website Sprachen hinzuzufügen. Kostenlos für alle! Besuchen Sie die Website hier:''',
        'implementation_title':'''Implementierungsanweisungen''',
        'implementation_description':'''Beispiel für die Implementierung''',
        'implementation_subject':'''Einfache Schritte zum Hinzufügen von Sprachen zur Website''',
        'implementation_info':'''Um einfache Schritte für eine mehrsprachige Website zu überprüfen, besuchen Sie bitte:''',
        'contact_title':'''Kontaktseite''',
        'contact_description':'''Kontaktinformationen''',
        'contact_subject':'''Kontaktiere uns''',
        'contact_info':'''Wenn Sie Unterstützung benötigen, verwenden Sie diese E -Mail für Kontakt:''',
        }
    if lang == 'de': return {
             'all_main':'''main''',
        'all_home':'''home''',
       
         'all_pages':'''pages''',
         'all_aboutus':'''About we''',
         'all_aboutus1':'''Wellcome to Afro Socker Ethiopia-''',

         'all_aboutus2':'''።sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate id est laborum.''',

         'all_aboutus3':'''Ius ferri velit sanctus cu, sed at soleat accusata. Dictas prompta et Ut placerat legendos interpre.Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante Etiam sit amet orci eget. Quis commodo odio aenean sed adipiscing. Turpis massa tincidunt dui ut ornare lectus. Auctor elit sed vulputate mi sit amet. Commodo consequat. Duis aute irure dolor in reprehenderit in voluptate id est laborum.''',

        'all_aboutus4':'''What We Provide? ''',
       'all_aboutus5':'''Best Prices & Offers''',
        'all_aboutus6':'''There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form''',
             'all_aboutus7':'''Read more''',
              'all_aboutus8':'''Wide Assortment''',
               'all_aboutus9':'''here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form''',
                
                 'all_aboutus11':'''Free Delivery''',

   'base':'''Afro Soccer Ethiopia''',
 'all_base1':'''Sale Off''',
 'all_base2':'''Add to cart''',
 'all_base3':'''Vendor''',
 'all_base4':'''FOOTBALL''',
 'all_base5':'''>MFG:''',
 'all_base6':''' Jun 4.2022''',

 'all_base7':''' We promote local players ''',
 'all_base8':'''AboutUs ''',
 'all_base9':'''Home''',

 'all_base10':'''Contact Us''',
 'all_base11':'''Afro soccer Ethiopia your best chaoice''',

 'all_base12':'''we promote local football players to the world''',
 'all_base13':'''we thank you since we you choose us''',
 'all_base14':''' meet our demand our sponsor coffe bank''',
 'all_base15':'''if you need help call as::''',
 'all_base16':'''All Categories''',
 'all_base17':'''Football''',
 'all_ baseacc':'''myaccount''',



 'all_baseh':'''Ethiopian Sport Hero''',
 'all_baser':'''EPL 2015 Match Results''',
 'all_basen':'''Sport News''',

'all_basen1':'''Updated Sport News''',
'all_basen2':'''Updated Transfer News''',
'all_basen4':'''Football Awards''',


'all_baset':'''Transfer News''',
 'all_basep':''' EPL Players''',
'all_basecl':''' EPL Clubs''',
  'all_basec':'''EPL Coachs''',
  'all_basez':'''Football Awards''',



 'all_basep0':'''Abubeker Nassir ''',
    'all_basep2':'''Mignot Debebe''',
 'all_basep3':'''Getaneh Kebede''',
  'all_basep4': '''Oumed Oukri''',
   'all_basep5':'''Suleman Hamid''',
   'all_basep6':'''Aschalew Tamener''',
   'all_basep7': '''Shemeles Bekele''',
  'all_basep8': '''Mignot Debebe''',
   'all_basep9':'''Dawit Estifanos''',
   'all_basep10':'''Ramadan Yusef''',
    'all_basep11':'''Beneyam Demte''',
 'all_basep12':'''   Saladin Bargicho''',
  'all_basep13':'''Amanuel Gebremichael''',
    'all_basep14':'''Fitsum Alemu''',
  'all_basep15': '''mujib Kassim''',
   'all_basep16':  '''Shemeles Bekele''',
  'all_basep17': '''Mesud Mohammed''',
   'all_basep18':'''Bezabeh Meleyo''',
   'all_basep19': '''Bereket Amare''',

     'all_basep20': '''abebe lema''',



'all_basec0':'''Ethiopia Bunna''',
    'all_basec2':'''Welayta Dicha''',
 'all_basec3':'''Welayta Dicha''',
  'all_basec4': '''Hawassa Kenema''',
   'all_basec5':'''Hadiya Hossana''',
   'all_basec6':'''Defence Force''',
   'all_basec7': '''Welayta Dicha''',
  'all_basec8': '''Faasil Kenema''',
   'all_basec9':'''Sidama Bunna''',
   'all_basec10':'''Saint Gorge Club''',
    'all_basec11':'''Faasil Kenema''',
 'all_basec12':'''   Adama Kenema''',
  'all_basec13':'''Bahrdar Kenema''',
    'all_basec14':'''>Wolayta Decha''',
  'all_basec15': '''Saint George S.C''',
   'all_basec16':  '''Sidama Bunna''',
   'all_basec7': '''Adama City''',
  'all_basec17': '''arba Minch City''',
   'all_basec18':'''Dashen Beer FC''',
   'all_basec19': '''Debub Police''',

     'all_basec20': '''Dire Dawa City''',


'all_basecl0':'''Wubetu Abate''',
    'all_basecl2':'''Abraham Mebratu''',
 'all_basecl3':'''Yohannes Sahle''',
  'all_basecl4': '''Yidnekatchew Tessema''',
   'all_basecl5':'''Gebremedhin Haile''',
   'all_basecl6':'''Mengistu Worku''',
   'all_basecl7': '''Ashenafi Bekele''',
  'all_basecl8': '''Yohannes Sahle''',
   'all_basecl9':'''Gebremedhin Haile''',
   'all_basecl10':'''Abraham Mebratu''',
    'all_basecl11':'''Wubetu Abate''',
 'all_basecl12':'''  Ashenafi Bekele''',
  'all_basecl13':'''Gebremedhin Haile''',
    'all_basecl14':'''Yohannes Sahle''',
  'all_basecl15': '''Gebremedhin Haile''',
   'all_basecl16':  '''Abraham Mebratu''',
   'all_basecll7': '''Wubetu Abate''',
  'all_basec17': '''Ashenafi Bekele''',
   'all_basecl18':'''Gebremedhin Haile''',
   'all_basecl19': '''Yohannes Sahle''',

     'all_basecl20': '''Yohannes Sahle''',

'all_basesup': '''Support Center''',
'l_base':'''Review''',

 'SUMMERY':'''SUMMERY''',
 'RESULTS':'''RESULTS''',

'FIXTURES':'''FIXTURES''',

'STANDING':'''STANDING''',

'ACHIVE':'''ACHIVE''',





        'all_implementation':'''Implementation''',
        'all_contact':'''Contact''',
        'home_title':'''Translations framework for Django''',
        'home_description':'''This is just an example for multi-language website''',
        'home_subject':'''Candy Translate''',
        'home_info':'''Easy and quick way to add languages to the website. Free for everyone! Visit the website here: ''',
        'implementation_title':'''Implementation instructions''',
        'implementation_description':'''Example of implementation''',
        'implementation_subject':'''Easy steps to add languages to the website''',
        'implementation_info':'''To check simple steps for having multi-language website please visit: ''',
        'contact_title':'''Contact page''',
        'contact_description':'''Contact information''',
        'contact_subject':'''Contact us''',
        'contact_info':'''If you need support please use this email for contact: ''',
        }

    if lang == 'es': return {
               'all_main':'''ተገገገረሀረሀተ''',
        'all_home':'''home''',
       
         'all_pages':'''pages''',
         'all_aboutus':'''About us''',
         'all_aboutus1':'''Wellcome to Afro Socker Ethiopia-እንኳን ወደ አፍሮ ሶከር ኢትዮጵያ በሰላም መጣቹ''',

         'all_aboutus2':'''አፍሮ ሶከር ኢትዮጵያ በኢትዮጵያ እግር ኳስ ላይ ትኩረቱን አድርጎ የሚሰራ የኦንላይን ሚድያ ነው።sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate id est laborum.''',

         'all_aboutus3':'''አፍሮ ሶከር ኢትዮጵያ በኢትዮጵያ እግር ኳስ ላይ ትኩረቱን አድርጎ የሚሰራ የኦንላይን ሚድያ ነውinterpre.Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante Etiam sit amet orci eget. Quis commodo odio aenean sed adipiscing. Turpis massa tincidunt dui ut ornare lectus. Auctor elit sed vulputate mi sit amet. Commodo consequat. Duis aute irure dolor in reprehenderit in voluptate id est laborum.''',

        'all_aboutus4':'''አቅርቦታችን''',
       'all_aboutus5':'''ምርጥ እቅርቦት''',
        'all_aboutus6':'''ብዚሀ ግጥ  እናንትነ የሚየስተምሩ but the majority have suffered alteration in some form''',
             'all_aboutus7':'''የብልጠ እንብብ''',
              'all_aboutus8':'''ተልቅ ሰጦታ''',
               'all_aboutus9':'''here are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form''',
               
                 'all_aboutus11':'''ስለ ሽቀረቦታችን
                  ''',



   
   'base':'''አፍሮ ሶከር ኢትዮጵያ''',
 'all_base1':'''Sale Off''',
 'all_base2':'''Add to cart''',
 'all_base3':'''Vendor''',
 'all_base4':'''FOOTBALL''',
 'all_base5':'''>MFG:''',
 'all_base6':''' Jun 4.2022''',

 'all_base7':''' የህገር ዉስጥ ተጫዋቾችን ''',
 'all_base8':'''AboutUs ስለእኛ''',
 'all_base9':'''Betting''',

 'all_base10':'''Login to your Betting Account''',
 'all_base11':'''አፍር ሶከር ኢትዮጵያ የናንተ ምርጫ''',

 'all_base12':'''የህገር ዉስጥ ተጫዋቾችን ለአለም እናስተዋውቃለን''',
 'all_base13':'''ምርጫቹ ስላደረርጋቹን እናመሰግናለለን''',
 'all_base14':''' የክብር ስፖንሰር-፟ቡና ኢንተርናሽናል ባንከ''',
 'all_base15':'''እገዛ ከፈለጉ?የደዉሉልን::''',
 'all_base16':'''All Categories''',
 'all_base17':'''Football''',
 'all_ baseacc':'''myaccount''',



 'all_baseh':'''የእኢትየኦጵየ ተጫዋቾች''',
 'all_baser':'''የ 2015 የእኢትየኦጵየ ፕርሚሊግ ውጥት
  ''',
 'all_basen':'''ስፖርት ዘና''',
'all_baset':'''የዝውውር ዝና''',
 'all_basep':''' የኢትየጵየ ተጫዋቾች''',
'all_basecl':''' የኢትየጵየ ክልቦች''',
  'all_basec':'''EPL አሰልጣኞች''',
  'all_base':'''የእግር ኩዋስ ሽልማት''',

'all_basesup': '''Support Center''',

        'all_implementation':'''Implementación''',
        'all_contact':'''Contacto''',
        'home_title':'''Marco de traducciones para Django''',
        'home_description':'''Este es solo un ejemplo para el sitio web de varios idiomas''',
        'home_subject':'''Los dulces traducir''',
        'home_info':'''Forma fácil y rápida de agregar idiomas al sitio web. ¡GRATIS para todos! Visite el sitio web aquí:''',
        'implementation_title':'''Instrucciones de implementación''',
        'implementation_description':'''Ejemplo de implementación''',
        'implementation_subject':'''Pasos sencillos para agregar idiomas al sitio web''',
        'implementation_info':'''Para verificar los pasos simples para tener un sitio web de varios idiomas, visite:''',
        'contact_title':'''Pagina de contacto''',
        'contact_description':'''Información del contacto''',
        'contact_subject':'''Contáctenos''',
        'contact_info':'''Si necesita soporte, use este correo electrónico para contactar:''',
        }


def detectLanguage(request):
    languageDetected = supported_languages[0]
    lastPath = request.path.split('/')[-1]
    if lastPath in supported_languages[1:]:
        languageDetected = lastPath
    return languageDetected


from django.urls import path as org_path
def path(route, view, kwargs=None, name=None):
    if route == '':
        return [org_path('', view, kwargs, name),org_path('de', view, kwargs, name+'_de'),org_path('es', view, kwargs, name+'_es'),]
    if route[-1] == '/': route=route[:-1]
    return [org_path(route, view, kwargs, name),org_path(route+'/de', view, kwargs, name+'_de'),org_path(route+'/es', view, kwargs, name+'_es'),]


def langRef(path_ref):
    last=path_ref.split('/')[-1]
    if last in supported_languages:
        path_ref=path_ref[:-len(last)-1]
    result='<link rel="alternate" hreflang="en" href="'+addLinks(path_ref,'')+'" />\n'
    result+='<link rel="alternate" hreflang="de" href="'+addLinks(path_ref,'de')+'" />\n'
    result+='<link rel="alternate" hreflang="es" href="'+addLinks(path_ref,'es')+'" />\n'
    result+='<link rel="alternate" hreflang="x-default" href="'+addLinks(path_ref,'')+'" />\n'
    return result


from django.urls import get_resolver
def translatedLinks(lang):
    names=[]
    for i in get_resolver().url_patterns:
        if hasattr(i, 'name'):
            if i.name:
                names.append(i.name)
    result = {}
    if lang == supported_languages[0]:
        for i in names:
            if i[-3:] not in ['_de', '_es'] and names.count(i+'_de'):
                result.update({i:i})
        return result
    for i in names:
        if names.count(i+'_'+lang):
            result.update({i:i+'_'+lang})
    return result


def languageMenu(path, lang):
    selected = [' ', ' ', ' ']
    selected[supported_languages.index(lang)]=' selected '
    if supported_languages.index(lang):
        path=path[:-3]
    result = '<select id="languageMenu" onchange="window.location = this.value;">'
    if path == '/': path = ''
    if path =='':
        result += '<option'+selected[0]+'value="/">Amharic (አማርኛ)</option>'
    else:
        result += '<option'+selected[0]+'value="' + path +'">Amharic (አማርኛ)</option>'
    result += '<option'+selected[1]+'value="' + path +'/de">Englishs (English)</option>'
    result += '<option'+selected[2]+'value="' + path +'/es">Arebic (አረበኛ)</option>'
    result += '</select>'
    return result


from django.shortcuts import render as org_render
def render(request, template_name, context=None, *args, **kwargs):
    lang=detectLanguage(request)
    if context == None:
        context={}
    return org_render(request, template_name, {**context,
                                                **translation_dictionary(lang),
                                                'lang':lang,
                                                'languageReferences':langRef(request.build_absolute_uri()),
                                                'languageMenu':languageMenu(request.path, lang),
                                                'candyLink':translatedLinks(lang),
                                                }, *args, **kwargs)


def addLinks(*args):
    result=''
    for i in args:
        if result and result[-1]=='/':result=result[:-1]
        if i and i[-1]=='/':i=i[:-1]
        if i and i[0]=='/':i=i[1:]
        if result and i: result+='/'
        result+=i
    return result


def provideSitemap(request, add_pages=[], remove_pages=[]):
    from django.http import HttpResponse
    result='<?xml version="1.0" encoding="UTF-8"?>'+'\n'
    result+='<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+'\n'
    domain= request.build_absolute_uri()
    domain=domain.split('/')[0]+'//'+domain.split('/')[2]+'/'
    paths = []
    for i in get_resolver().url_patterns:
        if str(type(i))=="<class 'django.urls.resolvers.URLPattern'>":
            route=i.pattern._route
            route=route.split('<')[0]
            if not route == 'sitemap.xml':
                paths.append(addLinks(domain,route))
    paths+=add_pages
    paths=list(dict.fromkeys(paths))
    for route in paths:
        if route not in remove_pages:
            result+='<url>'+'\n'
            result+='<loc>'+route+'</loc>'+'\n'
            result+='</url>'+'\n'
    result+='</urlset>'
    result= result.encode('utf-8')
    return HttpResponse(result, content_type='application/xml; charset=utf-8')


def sitemap(add_pages=[], remove_pages=[]):
    return [org_path('sitemap.xml', provideSitemap,{'add_pages' :add_pages,'remove_pages': remove_pages})]


